package com.evcharging.evchargingapp.data.model

data class Booking(
    val id: String,
    val ownerNic: String,
    val stationId: String,
    val stationName: String? = null,
    val reservationDate: String,
    val reservationHour: Int = 0, // Hour of the day (0-23), default to 0 for backward compatibility
    val status: String, // Pending, Approved, Cancelled, Completed
    val createdAt: String,
    val amount: Double? = null,
    val qrBase64: String? = null // QR code generated by backend when booking is approved
)

data class BookingStatusUpdateRequest(
    val status: String
)